### ISSUE TITLE
Index out of range when trying to deserialize

### ISSUE THREAD

**Issue by michalsrutek** [mongo-dart/bson#33]
When trying to use the library using the following code
```dart
  final serialized = BSON().serialize({'id': 42});
  final deserialized = BSON().deserialize(serialized);
```

I get 

```
Unhandled Exception: RangeError (index): Index out of range: index should be less than 13: 17
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2221:7)
#1      BsonBinary.readByte (package:bson/src/types/binary.dart:256:29)
#2      BsonMap.extractData (package:bson/src/types/map.dart:13:27)
#3      BSON.deserialize (package:bson/src/bson_impl.dart:19:20)
#4      main (package:cool_tests/main.dart:35:31)
```

Am I using it in a wrong way?

**Comment by giorgiofran** [comment]
You should reset the buffer offset before deserializing:
```dart
  final serialized = BSON().serialize({'id': 42});
  serialized.offset = 0;
  final deserialized = BSON().deserialize(serialized);
```
I will change it so that `deserialize` will do it internally without an explicit call.

**Comment by michalsrutek** [comment]
@giorgiofran Thank you, that works. I did not think of that!
